version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ec2-user/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: self-hosted
    group: self-hosted
        
hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: self-hosted
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: self-hosted
